name: Bug
about: Relatar um bug
labels: bug
name: Bug
description: Reporte um problema
labels: [bug]
body:
  - type: textarea
    id: steps
    attributes:
      label: Passos para reproduzir
      placeholder: 1) ... 2) ...
  - type: textarea
    id: expected
    attributes:
      label: Comportamento esperado
  - type: textarea
    id: actual
    attributes:
      label: O que aconteceu
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / gravações
  - type: input
    id: env
    attributes:
      label: Ambiente (navegador, SO)
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Adicione imagens se possível
      placeholder: "Cole aqui as imagens ou links"
    validations:
      required: false
