blank_issues_enabled: false
contact_links:
  - name: Discussões
    url: https://github.com/SEU_USUARIO/tiotor/discussions
    about: Ideias gerais e perguntas rápidas
contact_links:
  - name: Formulário de sugestão
    url: https://forms.gle/tiotor-feedback
    about: Use para enviar ideias, bugs ou melhorias se preferir.
