name: Ideia (sem código)
description: Sugira perguntas, textos, feedbacks de experiência
labels: [non-code, help wanted]
body:
  - type: textarea
    id: idea
    attributes:
      label: Sua sugestão
      placeholder: Nova pergunta para o tópico X...
  - type: textarea
    id: why
    attributes:
      label: Por quê isso ajuda?
