name: Melhoria
about: Sugira melhorias de UX, fluxo ou textos
labels: melhoria, ux
body:
  - type: input
    id: title
    attributes:
      label: Título
      description: Resuma a melhoria
      placeholder: "Exemplo: Botão 'Estou pronto' mais visível"
    validations:
      required: true
name: Melhoria (UX/Docs/Copy)
description: Proponha uma melhoria incremental
labels: [enhancement, docs, design]
body:
  - type: textarea
    id: change
    attributes:
      label: O que melhorar
  - type: textarea
    id: rationale
    attributes:
      label: Justificativa (cite princípios/obras)
      placeholder: Maeda – The Laws of Simplicity; Erika Hall – Conversational Design...
